/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MinimalForwarder } from "./MinimalForwarder";
export * as factories from "./factories";
export { MinimalForwarder__factory } from "./factories/MinimalForwarder__factory";
